### ISSUE TITLE
how run

### ISSUE THREAD

**Issue by jujes** [wpioneer/telescope-looknows#1]
I'm new in meteor/telescope and need install your telescope-looknows whit this script but don't get success.. can you tell me how?
thank in advance.

```
curl https://install.meteor.com/ | sh
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y git

git clone https://github.com/TelescopeJS/Telescope

git clone https://github.com/wpioneer/telescope-looknows.git
mv ~/telescope-looknows/lib ~/Telescope
mv ~/telescope-looknows/package.js ~/Telescope

cd Telescope
meteor




		=> Exited with code: 8
```

**Comment by wpioneer** [comment]
Hi,
Telescope-looknows Package is not compatible with the current version of the telescope. But it works just fine with the version v0.21.1.
Therefore, if you have time, you can update =)

## Installing

	curl https://install.meteor.com/ | sh

	git clone https://github.com/TelescopeJS/Telescope.git

	cd Telescope
	git checkout tags/v0.21.1

	cd packages
	git clone https://github.com/wpioneer/telescope-looknows.git

	cd ../

	meteor add wpioneer:theme-looknows
	meteor


After installation, visit the settings to change Post Layout option.
